### ISSUE TITLE
dateline havoc

### ISSUE THREAD

**Issue by voj** [GNS-Science/nshm-nz-opensha#126]
This fault crosses the dateline and we can't create subsections

```XML
    <i260 sectionId="260" sectionName="Kermadec Trench" aveLongTermSlipRate="0.0" slipRateStdDev="0.0" aveDip="30.0" aveRake="-90.0" aveUpperDepth="0.0" aveLowerDepth="14.0" aseismicSlipFactor="0.0" couplingCoeff="1.0" dipDirection="303.2" parentSectionId="-1" connector="false">
      <FaultTrace name="Kermadec Trench">
        <Location Latitude="-37.4019" Longitude="-179.9341" Depth="0.0000"/>
        <Location Latitude="-37.4832" Longitude="-179.9563" Depth="0.0000"/>
       <Location Latitude="-37.7583" Longitude="179.8024" Depth="0.0000"/>
      </FaultTrace>
    </i260>
```

```
Get subSections in Kermadec Trench
260
Kermadec Trench
ddw: 28.000000000000004
maxSectLength: 14.000000000000002
Exception in thread "main" java.lang.IllegalArgumentException: Value [-180.0467781820897] out of range [-180.0 ,360.0]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:459)
	at org.opensha.commons.util.DataUtils.validate(DataUtils.java:620)
	at org.opensha.commons.geo.GeoTools.validateLon(GeoTools.java:159)
	at org.opensha.commons.geo.Location.<init>(Location.java:89)
	at org.opensha.commons.geo.LocationUtils.location(LocationUtils.java:547)
	at org.opensha.commons.geo.LocationUtils.location(LocationUtils.java:524)
	at org.opensha.commons.util.FaultUtils.getEqualLengthSubsectionTraces(FaultUtils.java:205)
	at org.opensha.refFaultParamDb.vo.FaultSectionPrefData.getSubSectionsList(FaultSectionPrefData.java:422)
	at org.opensha.refFaultParamDb.vo.FaultSectionPrefData.getSubSectionsList(FaultSectionPrefData.java:33)
	at nz.cri.gns.NZSHM22.opensha.ruptures.NZSHM22_RuptureSetBuilder.loadFaults(NZSHM22_RuptureSetBuilder.java:390)
	at nz.cri.gns.NZSHM22.opensha.ruptures.NZSHM22_RuptureSetBuilder.buildRuptureSet(NZSHM22_RuptureSetBuilder.java:442)
	at nz.cri.gns.NZSHM22.opensha.scripts.scriptCrustalInversionRunner.generateRuptures(scriptCrustalInversionRunner.java:141)
	at nz.cri.gns.NZSHM22.opensha.scripts.scriptCrustalInversionRunner.main(scriptCrustalInversionRunner.java:214)
```

This fault probably crosses under the dateline, and we can't create a Stirling surface
```XML
    <i260 sectionId="260" sectionName="Kermadec Trench" aveLongTermSlipRate="0.0" slipRateStdDev="0.0" aveDip="30.0" aveRake="-90.0" aveUpperDepth="0.0" aveLowerDepth="14.0" aseismicSlipFactor="0.0" couplingCoeff="1.0" dipDirection="303.2" parentSectionId="-1" connector="false">
      <FaultTrace name="Kermadec Trench">
        <Location Latitude="-37.4019" Longitude="-179.9341" Depth="0.0000"/>
        <Location Latitude="-37.4832" Longitude="-179.9563" Depth="0.0000"/>
      </FaultTrace>
    </i260>
```

```
Exception in thread "main" java.lang.IllegalArgumentException: Value [-180.00535245614554] out of range [-180.0 ,360.0]
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:459)
	at org.opensha.commons.util.DataUtils.validate(DataUtils.java:620)
	at org.opensha.commons.geo.GeoTools.validateLon(GeoTools.java:159)
	at org.opensha.commons.geo.Location.<init>(Location.java:89)
	at org.opensha.commons.geo.LocationUtils.location(LocationUtils.java:547)
	at org.opensha.commons.geo.LocationUtils.location(LocationUtils.java:524)
	at org.opensha.sha.faultSurface.StirlingGriddedSurface.createEvenlyGriddedSurface(StirlingGriddedSurface.java:287)
	at org.opensha.sha.faultSurface.StirlingGriddedSurface.<init>(StirlingGriddedSurface.java:97)
	at org.opensha.refFaultParamDb.vo.FaultSectionPrefData.getStirlingGriddedSurface(FaultSectionPrefData.java:557)
	at org.opensha.refFaultParamDb.vo.FaultSectionPrefData.getFaultSurface(FaultSectionPrefData.java:527)
	at org.opensha.refFaultParamDb.vo.FaultSectionPrefData.getFaultSurface(FaultSectionPrefData.java:33)
	at org.opensha.sha.earthquake.faultSysSolution.ruptures.util.SectionDistanceAzimuthCalculator.<init>(SectionDistanceAzimuthCalculator.java:48)
	at nz.cri.gns.NZSHM22.opensha.ruptures.NZSHM22_RuptureSetBuilder.buildConfig(NZSHM22_RuptureSetBuilder.java:407)
	at nz.cri.gns.NZSHM22.opensha.ruptures.NZSHM22_RuptureSetBuilder.buildRuptureSet(NZSHM22_RuptureSetBuilder.java:444)
	at nz.cri.gns.NZSHM22.opensha.scripts.scriptCrustalInversionRunner.generateRuptures(scriptCrustalInversionRunner.java:141)
	at nz.cri.gns.NZSHM22.opensha.scripts.scriptCrustalInversionRunner.main(scriptCrustalInversionRunner.java:214)
```

**Comment by chrisbc** [comment]
@voj FYI we had a similar issue with rupture sets based on the recent kermadec subduction data, which also crossed the dateline. But it was:

**Comment by voj** [comment]
this will hopefully be fixed by https://github.com/GNS-Science/eq-fault-geom/issues/55

**Comment by voj** [comment]
works with those changes
