### ISSUE TITLE
Find root cause for Problem Mmax exception in StandaloneSubSectRupGenMG

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-nz-opensha#47]
Running StandaloneSubSectRupGenMG raises an exception

using latest CFM faults dataset `/data/FaultModels/DEMO2_DIPFIX_crustal_opensha.xml`

```
Exception in thread "main" java.lang.RuntimeException: Problem Mmax: -0.15000000000000002	Ariel East, Subsection 0	BRANCH: LogicTreeBranch[FM3_1, GEOL, Shaw09Mod, DsrTap, CharConst, M5Rate7.9, MMaxOff7.6, NoFix, SpatSeisU3]
	at scratch.UCERF3.analysis.FaultSystemRupSetCalc.getCharSubSeismoOnFaultMFD_forEachSection(FaultSystemRupSetCalc.java:1295)
	at scratch.UCERF3.inversion.InversionTargetMFDs.<init>(InversionTargetMFDs.java:245)
	at scratch.UCERF3.inversion.InversionFaultSystemRupSet.calcRuptureAttributes(InversionFaultSystemRupSet.java:354)
	at scratch.UCERF3.inversion.InversionFaultSystemRupSet.<init>(InversionFaultSystemRupSet.java:158)
	at scratch.kevin.ucerf3.StandaloneSubSectRupGenMG.main(StandaloneSubSectRupGenMG.java:207)
```

**Comment by chrisbc** [comment]
@voj this one just might shed some light on things upstream. I've confirmed that the error is still being raised with StandaloneSubSectRupGenMG configured as per https://github.com/GNS-Science/nshm-nz-opensha/pull/50/commits/20f200b66542a5fa0d4077814c050f987b12d71a and using either of the two files: **DEMO2_*.xml** 

It only takes a minute or so to fail on my machine using these settings.  

I cannot be sure this relates to the latest upstream merges, but I've not seen this particular error until just this week.

**Comment by chrisbc** [comment]
@voj So it turns out that the implementation of SlipAlongRuptureModelRupSet (which assembles the ruptset zip file) is different in the two scripts (**Standalone** vs **scriptCrustal**). Only the the older implementation used in **Standalone** raises this error.

Will need to look at why this is and what we do going forward - with some @kevinmilner advice needed I think :).

**Comment by voj** [comment]
@chrisbc is this still relevant now that it only affects an older version?

**Comment by chrisbc** [comment]
> @chrisbc is this still relevant now that it only affects an older version?

It's because the error is happening somewhere in core opensha code. The older standAlone.... code is using that core code, while our latest (based on Kevins example) does not. I think we should understand why not, and whether we can/should refactor the new stuff / fix the problem.
